service/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('submit-form/', views.submit_form, name='submit_form'),
    path('login/', views.login_view, name='login'),
    path('register/', views.signup_view, name='register'),
    path('profile/', views.profile_view, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(template_name='auth/logout.html'), name='logout'),
    path('about_company/', views.about_company, name='about'),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('reviews/', views.reviews, name='reviews'),
    path('add-review/', views.add_review, name='add_review'),
    path('toggle-review/<int:review_id>/', views.toggle_review, name='toggle_review'),
    path('delete-review/<int:review_id>/', views.delete_review, name='delete_review'),
    path('news/', views.news_page, name='news_page'),
    path('news/delete/<int:news_id>/', views.delete_news, name='delete_news'),
    path('news/<int:news_id>/edit/', views.update_news, name='update_news'),
    path('news/add/', views.add_news, name='add_news'),
    path('contacts/', views.contacts_page, name='contacts'),
    path('services/', views.services_price, name='services'),
]

service/service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_header = 'Admin'
admin.site.site_title = 'Admin Panel'
admin.site.index_title = 'Welcome'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

service/app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from django.utils import timezone


class CustomUser(AbstractUser):
    phone_number = models.CharField(
        max_length=15, blank=True, null=True, verbose_name="Телефон"
    )
    avatar = models.ImageField(
        upload_to="avatars/", blank=True, null=True, verbose_name="Аватар"
    )

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.username
    

class ServicesPrice(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название работы')
    price = models.CharField(max_length=100, verbose_name='Цена')
    
    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'

    def __str__(self):
        return self.title

class TeamMembers(models.Model):
    name = models.CharField(max_length=50, verbose_name='Имя')
    type = models.CharField(max_length=50, verbose_name='Тип работы')
    image = models.ImageField(upload_to='member_images/', verbose_name='Изображение', blank=True, null=True)

    class Meta:
        verbose_name = 'Работник'
        verbose_name_plural = 'Работники'

    def __str__(self):
        return self.name
    

class News(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержание')
    image = models.ImageField(upload_to='news_images/', verbose_name='Изображение', blank=True, null=True)
    
    created_at = models.DateTimeField(default=timezone.now, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ['-created_at']

    def __str__(self):
        return self.title


class UserReviews(models.Model):
    user = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name="reviews",
        verbose_name="Пользователь",
    )
    text = models.TextField(verbose_name="Текст отзыва")
    rating = models.PositiveSmallIntegerField(
        choices=[(i, str(i)) for i in range(1, 6)], verbose_name="Рейтинг"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    is_published = models.BooleanField(default=True, verbose_name="Опубликовано")

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Отзыв от {self.user.username}"


class UserProfile(models.Model):
    user = models.OneToOneField(
        get_user_model(), on_delete=models.CASCADE, related_name="userprofile"
    )

    def __str__(self):
        return f"Профиль {self.user.username}"


class CarServiceRequest(models.Model):
    STATUS_CHOICES = [
        ("new", "Новая"),
        ("in_progress", "В работе"),
        ("completed", "Завершена"),
        ("canceled", "Отменена"),
    ]

    user = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, null=True, blank=True
    )
    
    name = models.CharField(max_length=100, verbose_name="Имя")
    phone = models.CharField(max_length=20, verbose_name="Телефон")
    car_brand = models.CharField(max_length=50, verbose_name="Марка автомобиля")
    problem_description = models.TextField(
        verbose_name="Описание проблемы", null=True, default="Не указано"
    )
    
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    service_date = models.DateField(
        verbose_name="Дата обслуживания", null=True, blank=True
    )

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new')

    class Meta:
        verbose_name = "Заявка на сервис"
        verbose_name_plural = "Заявки на сервис"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Заявка #{self.id} - {self.car_brand} ({self.get_status_display()})"

service/app/templates/app/about_company.html
{% load static %}

{% include "app/header.html" %}

<head>
    <link rel="stylesheet" href="{% static 'app/css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/about_company.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>


<main>

    <body>
        <section>
            <div class="about__company_section">
                <div class="information">
                    <strong>О компании</strong>
                    <h1>Кто мы?</h1>
                    <p>
                        Автосервис «SpeedyMech» осуществляет разнообразные виды работ в строгом соответствии
                        с рекомендациями производителей на современном оборудовании. <br>
                        <br>
                        Ремонт автомобилей в автосервисе производят квалифицированные
                        специалисты, что обеспечивает высокое качество выполненных работ.
                        Профессионалы, обладающие знаниями и специальной подготовкой,
                        подтвержденной сертификатами, осуществляют сервисные работы, ремонт
                        и замену запасных деталей, диагностику и техническое обслуживание автомобилей
                        любых марок. Компания постоянно совершенствует производственный процесс, чтобы
                        сократить время ремонта и техобслуживания. <br>
                        <br>
                        Автосервис «SpeedyMech» предоставляет владельцам автомобилей все виды услуг в г.
                        Ижевск. Для удобства клиентов заявку на проведение ТО или ремонт можно сделать
                        на сайте компании, что исключит трату времени на ожидание в очереди. Полный перечень
                        производимых услуг, их стоимость, предоставлен на нашем сайте.
                    </p>
                </div>

                <div class="about__company_items">
                    <h2>Наше оборудование</h2>
                    <div class="about__company_list_item">
                        <div class="about__company_item">
                            <img src="{% static 'app/media/products/press.png' %}" alt="">
                            <p>Гидравлический пресс</p>
                        </div>
                        <div class="about__company_item">
                            <img src="{% static 'app/media/products/pod.jpg' %}" alt="">
                            <p>Подъемник</p>
                        </div>
                        <div class="about__company_item">
                            <img src="{% static 'app/media/products/wheel.jpg' %}" alt="">
                            <p>Шиномонтажный стенд</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </body>
</main>

{% include "app/footer.html" %}

service/app/templates/app/contacts_page.html
{% load static %}

<link rel="stylesheet" href="{% static 'app/css/style.css' %}">
<link rel="stylesheet" href="{% static 'app/css/header.css' %}">
<link rel="stylesheet" href="{% static 'app/css/contacts_page.css' %}">


{% include "app/header.html" %}


<main>
    <div class="contacts_page__container">

        <div class="connection">
            <h1>Как с нами связаться?</h1>
                <ol class="con_items">
                    <li class="con_item">
                        <a href="https://vk.com/sayykkk" target="_blank">
                            <img src="{% static 'app/media/icons/vk.png' %}" alt="">
                        </a>
                    </li>

                    <li class="con_item">
                        <a href="https://t.me/sayyk0" target="_blank">
                            <img src="{% static 'app/media/icons/tg.png' %}" alt="">
                        </a>
                    </li>

                    <li class="con_item">
                        <a href="">
                            <img src="{% static 'app/media/icons/wa.png' %}" alt="">
                        </a>
                    </li>

                    <li class="con_item">
                        <a href="">
                            <img src="{% static 'app/media/icons/viber.png' %}" alt="">
                        </a>
                    </li>
                </ol>
        </div>

        <div class="location">
            <h1>Наше местоположение</h1>

            <iframe
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4240.389445924271!2d53.20388592904512!3d56.840434925369905!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x43e139342b3043c1%3A0xbffaba6a591a2958!2z0YPQuy4g0JzQsNC60YHQuNC80LAg0JPQvtGA0YzQutC-0LPQviwgNDksINCY0LbQtdCy0YHQuiwg0YDQtdGB0L_Rg9Cx0LvQuNC60LAg0KPQtNC80YPRgNGC0LjRjywgNDI2MDA4!5e0!3m2!1sru!2sru!4v1745668748235!5m2!1sru!2sru"
                width="600" height="350" style="border:1px solid black; border-radius: 10px; " allowfullscreen=""
                loading="lazy" referrerpolicy="no-referrer-when-downgrade">
            </iframe>
        </div>
        
    </div>

</main>

{% include "app/footer.html" %}

service/app/templates/app/edit_news.html
{% load static %}

<link rel="stylesheet" href="{% static 'app/css/style.css' %}">
<link rel="stylesheet" href="{% static 'app/css/news_style.css' %}">
<link rel="stylesheet" href="{% static 'app/css/header.css' %}">

{% include "app/header.html" %}

<main class="edit_page">
    <h2>Редактирование новости</h2>
    <form action="{% url 'update_news' news.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">{{ form.title.label }}</label>
            <input type="text" name="title" value="{{ news.title }}">
        </div>

        <div class="form-group">
            <label for="id_title">{{ form.content.label }}</label>
            <textarea name="content">{{ news.content }}</textarea>
        </div>

        <div class="form-group">
            <input type="file" name="image">
            {% if news.image %}
            <p>Текущее изображение: <a href="{{ news.image.url }}">{{ news.image.name }}</a></p>
            {% endif %}
        </div>
        <button type="submit">Сохранить изменения</button>
        <a href="{% url 'news_page' %}">Отмена</a>
    </form>
</main>

service/app/templates/app/footer.html
{% load static %}

<link rel="stylesheet" href="{% static 'app/css/footer.css' %}">

<footer>
    <div class="footer">
        <div class="footer__head">
            <h1>
                Проблема с автомобилем? Мы поможем!
            </h1>
            <form action="" method="post">
                <input type="tel" placeholder="+7 (000) 000-0000">
                <button type="submit">Связаться с нами</button>
            </form>
            <small>
                Оставляя заявку, вы соглашаетесь на 
                обработку персональных данных и с условиями бронирования счёта
            </small>
        </div>

        <div class="footer__down">
            <div class="copyright">
                <p>Copyright 2025. SpeedyMech</p>
            </div>

            <div class="footer_nav">
                <ol>
                    <li class="site_nav"><a href="{% url 'about' %}">О компании</a></li>
                    <li class="site_nav"><a href="{% url 'news_page' %}">Новости</a></li>
                    <li class="site_nav"><a href="{% url 'services' %}">Цены</a></li>
                    <li class="site_nav"><a href="{% url 'contacts' %}">Контакты</a></li>
                </ol>
            </div>

            <div class="contacts">
                <p>+7 983 452 25-09</p>
                <p>SpeedyMech@example.com</p>
            </div>

            <div class="footer_link">
                <nav>
                    <ol>
                        <li class="link"><a href=""><img src="{% static 'app/media/icons/vk.png' %}" alt="vk"></a></li>
                        <li class="link"><a href=""><img src="{% static 'app/media/icons/inst.png' %}" alt="instagram"></a></li>
                        <li class="link"><a href=""><img src="{% static 'app/media/icons/youtube.png' %}" alt="youtube"></a></li>
                        <li class="link"><a href=""><img src="{% static 'app/media/icons/tg.png' %}" alt="telegram"></a></li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</footer>

service/app/templates/app/header.html
{% load static %}

<link rel="stylesheet" href="{% static 'app/css/header.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<header>
        <div class="logotype">
            <a href="{% url 'index' %}">
                <img src="{% static 'app/media/logo.png' %}" alt="Logo">
            </a>
        </div>
        <div class="header__items">
            <nav>
                <ul>
                    <li><a href="{% url 'about' %}">О компании</a></li>
                    <li><a href="{% url 'news_page' %}">Новости</a></li>
                    <li><a href="{% url 'index' %}#section5">Цены</a></li>
                    <li><a href="{% url 'reviews' %}">Отзывы</a></li>
                    <li><a href="{% url 'contacts' %}">Контакты</a></li>
                </ul>
            </nav>
            {% if user.is_authenticated %}
            <div class="personal__page">
                <a href="{% url 'profile' %}">
                    {% if user.avatar %}
                    <img src="{{ user.avatar.url }}" title="Личный кабинет" style="width: 45px;" alt="404">
                    {% endif %}

                    <div class="personal__page_names">
                        <p>{{ user.username }}</p>
                        <p>{{ user.phone_number }}</p>
                    </div>
                </a>
                <span></span>
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" title="Выход" style="border: none; background-color: transparent;">
                        <img src="{% static 'app/media/icons/logout.png' %}" style="width: 35px;" alt="">
                    </button>
                </form>
            </div>
            {% endif %}
            <div class="number">
                <p>Служба продаж</p>
                <strong>+7 495 123-45-67</strong>
            </div>
        </div>


</header>

service/app/templates/app/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    <title>SpeedyMech</title>

    <style>
        @media (max-width: 1024px) {
            .services_list ul {
                grid-template-columns: repeat(2, 1fr);
            }

            .team_members {
                grid-template-columns: repeat(2, 1fr);
            }
        }

        @media (max-width: 768px) {
            .upper_block {
                flex-direction: column;
            }

            .about_block {
                flex-direction: column;
            }



            .team_members {
                grid-template-columns: 1fr;
            }

            .text_block,
            .form_block,
            .about_us,
            .image_block {
                width: 100%;
            }
        }

        @media (max-width: 480px) {

            .block,
            .about_block,
            .services_block,
            .services_information,
            .services_background,
            .team {
                padding: 10px;
            }

            h1 {
                font-size: 24px;
            }
        }

        .notification-toast {
            position: fixed;
            bottom: 20px;
            right: 20px;
            padding: 15px 25px;
            border-radius: 5px;
            color: white;
            background: #333;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
            transform: translateY(100px);
            opacity: 0;
            transition: all 0.3s ease;
            z-index: 1000;
            max-width: 300px;
        }

        .notification-toast.show {
            transform: translateY(0);
            opacity: 1;
        }

        .notification-toast.success {
            background: #4CAF50;
        }

        .notification-toast.error {
            background: #F44336;
        }

        .notification-toast.warning {
            background: #FF9800;
        }

        .notification-toast.info {
            background: #2196F3;
        }
    </style>
</head>

<body>
    {% include "app/header.html" %}

    {% if messages %}
    <div id="notification-toast" class="notification-toast"></div>
    {% endif %}
    <main>
        <section>
            <div class="block">
                <div class="upper_block">
                    <div class="text_block">
                        <h1>Автосервис в Вашем городе</h1>
                        <p>
                            Мы надежный автосервис, который
                            ищет индивидуальный подход к каждому клиенту
                        </p>
                    </div>
                    <div class="form_block">
                        <p>Запишитесь на бесплатный осмотр подвески прямо сейчас</p>
                        <form action="{% url 'submit_form' %}" method="post">
                            {% csrf_token %}
                            {{ form.non_field_errors }}

                            <div class="form-group">
                                <input type="text" name="name" class="form-control" placeholder="Ваше имя" required
                                    value="{{ form.name.value|default_if_none:'' }}">
                                {{ form.name.errors }}
                            </div>

                            <div class="form-group">
                                <input type="tel" name="phone" class="form-control"
                                    placeholder="Контактный номер телефона" required
                                    value="{{ form.phone.value|default_if_none:'' }}">
                                {{ form.phone.errors }}
                            </div>

                            <div class="form-group">
                                <input type="text" name="car_brand" class="form-control" placeholder="Марка автомобиля"
                                    required value="{{ form.car_brand.value|default_if_none:'' }}">
                                {{ form.car_brand.errors }}
                            </div>


                            <div class="form-group">
                                <textarea name="problem_description" class="form-control"
                                    placeholder="Описание проблемы" id="" required
                                    value="{{ form.problem_description.value|default_if_none:'' }}"></textarea>
                                {{ form.car_brand.errors }}
                            </div>

                            <button type="submit" {% if not user.is_authenticated %}disabled
                                title="Для записи необходимо авторизоваться" {% endif %}>
                                Оставить заявку
                            </button>

                            {% if not user.is_authenticated %}
                            <p class="auth-warning">
                                Для записи необходимо <a
                                    href="{% url 'login' %}?next={{ request.path }}">авторизоваться</a>
                            </p>
                            {% endif %}
                        </form>
                        <strong>Акция действует до 12.06.2025</strong>
                    </div>
                </div>
            </div>
        </section>

        <section>
            <div class="about_block">
                <div class="about_us">
                    <strong>О компании</strong>
                    <h1>Честный ремонт автомобилей</h1>
                    <p>
                        Диагностика, техобслуживание, шиномонтаж, кузовной и малярный ремонт любой сложности.
                        <br> <br>
                        Быстро, насколько это возможно. Профессионально и аккуратно.
                        Без обмана и непредвиденных трат. С максимальным вниманием к вашей проблеме.
                    </p>
                    <a href="{% url 'about' %}">Подробнее</a>
                </div>

                <div class="image_block">
                    <img class="rectangle_image_1" src="{% static 'app/media/products/Rectangle1.png' %}" alt="image1">
                    <img class="rectangle_image_2" src="{% static 'app/media/products/Rectangle2.png' %}" alt="image2">
                </div>
            </div>
        </section>

        <section class="services_section">
            <div class="services_block">
                <div class="services_title">
                    <h1>Ремонтируем всё</h1>
                    <p>Наши возможности и габариты позволяют ремонтировать даже броневики.</p>
                </div>
                <div class="services_list">
                    <div class="service_item">
                        <nav>
                            <ul>
                                <li>
                                    <img src="{% static 'app/media/icons/mark.png' %}" alt="">
                                    <h2>Ремзона</h2>
                                    <p>Площадь ремзоны 1000 м2</p>
                                </li>

                                <li>
                                    <img src="{% static 'app/media/icons/ware.png' %}" alt="">
                                    <h2>Склад</h2>
                                    <p>Собственный склад запчастей</p>
                                </li>

                                <li>
                                    <img src="{% static 'app/media/icons/posts.png' %}" style="width: 33px;" alt="">
                                    <h2>10 постов</h2>
                                    <p>10 ремонтных постов</p>
                                </li>

                                <li>
                                    <img src="{% static 'app/media/icons/wheel.png'%}" alt="">
                                    <h2>Развал-схождение</h2>
                                    <p>4-х стоечный подъёмник для развал-схождения
                                        и подъёма крупных автомобилей</p>
                                </li>

                                <li>
                                    <img src="{% static 'app/media/icons/wrench.png' %}"
                                        style="width: 30; height: 40px;" alt="">
                                    <h2>4 цеха</h2>
                                    <p>4 цеха: слесарный, кузовной, малярный и арматурный</p>
                                </li>

                                <li>
                                    <img src="{% static 'app/media/icons/man.png' %}" style="width: 40; height: 40px;"
                                        alt="">
                                    <h2>Специалисты</h2>
                                    <p>18 специалистов с профильной высокой квалификации</p>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </section>

        <section>
            <div class="services_information">
                <img src="{% static 'app/media/products/recc.png' %}" style="width: 64px; height: 48px;" alt="Image">
                <h1>Наш сертифицированный автосервис предоставляет гарантию на 1 год.</h1>
                <p>— Иван Иванов, директор</p>
            </div>
        </section>

        <section id="section5">
            <div class="services_background">
                <div class="services_price">
                    <h1>Наши услуги</h1>
                    <p>Консультация входит в стоимость</p>
                    <ol>
                        <li class="item">Кузовной ремонт<p class="price">от 1000 ₽</p>
                        </li>

                        <span></span>

                        <li class="item">Малярные работы<p class="price">от 4000 ₽</p>
                        </li>

                        <span></span>

                        <li class="item">Слесарные работы<p class="price">от 500 ₽</p>
                        </li>

                        <span></span>

                        <li class="item">Техобслуживание<p class="price">от 300 ₽</p>
                        </li>

                        <span></span>

                        <li class="item">Автоэлектрика<p class="price">от 750 ₽</p>
                        </li>

                        <span></span>

                        <li class="item">Диагностика<p class="price">от 450 ₽</p>
                        </li>

                    </ol>

                    <a href="{% url 'services' %}">Подробнее</a>

                    <small>Оставляя заявку, вы соглашаетесь на обработку
                        персональных данныхыи с условиями бронирования счёта</small>
                </div>
            </div>
        </section>

        <section>
            <div class="team">
                <span>Команда</span>
                <h1>Кто мы?</h1>
                <p>
                    Наша команда собрана исключительно из
                    профессионалов своего дела, которые работаю на ваше благо
                </p>
                <div class="team_members">
                    {% for member in members %}
                    <div class="team_member">
                        <img src="{{ member.image.url }}" alt="team_member">
                        <p>{{ member.name }}</p>
                        <strong>{{ member.type }}</strong>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </main>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const toast = document.getElementById('notification-toast');

            {% if messages %}
            {% for message in messages %}
            showToast('{{ message|escapejs }}', '{{ message.tags }}');
            {% endfor %}
            {% endif %}

            function showToast(text, type) {
                if (!toast) return;

                toast.textContent = text;
                toast.className = 'notification-toast show ' + type;

                setTimeout(function () {
                    toast.classList.remove('show');
                }, 5000);
            }
        });
    </script>

</body>

{% include "app/footer.html" %}

</html>

service/app/templates/app/new_add.html
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/news_style.css' %}">
</head>

{% include "app/header.html" %}


<main>
    <div class="container">
        <h2>Добавить новость</h2>
        <form method="post" enctype="multipart/form-data" class="add_news__form">
            {% csrf_token %}
            
            <div class="form-group">
                <label for="{{ form.title.id_for_label }}" class="form-label">{{ form.title.label }}</label>
                {{ form.title }}
                {% if form.title.errors %}
                    <div class="invalid-feedback d-block">
                        {{ form.title.errors }}
                    </div>
                {% endif %}
            </div>
            
            <div class="form-group">
                <label for="{{ form.content.id_for_label }}" class="form-label">{{ form.content.label }}</label>
                {{ form.content }}
                {% if form.content.errors %}
                    <div class="invalid-feedback d-block">
                        {{ form.content.errors }}
                    </div>
                {% endif %}
            </div>
            
            <div class="form-group">
                <label for="{{ form.image.id_for_label }}" class="form-label">{{ form.image.label }}</label>
                {{ form.image }}
                {% if form.image.errors %}
                    <div class="invalid-feedback d-block">
                        {{ form.image.errors }}
                    </div>
                {% endif %}
            </div>
            
            <div class="form-check">
                {{ form.is_published }}
                <label for="{{ form.is_published.id_for_label }}" class="form-check-label">{{ form.is_published.label }}</label>
            </div>
            
            <button type="submit" class="btn btn-primary">Опубликовать</button>
        </form>
    </div>
</main>

service/app/templates/app/services.html
{% load static %}

<link rel="stylesheet" href="{% static 'app/css/style.css' %}">
<link rel="stylesheet" href="{% static 'app/css/services.css' %}">

<title>{{ title }}</title>

{% include "app/header.html" %}


<main>
    <div class="services_container">
        <h1>Прайс-лист</h1>
        <div class="prices">
            {% for i in price %}
            <ol class="price-list">
                <li class="service">
                    <span class="service-name">{{ i.title }}</span>
                    <span class="service-price">от {{ i.price }} ₽</span>
                </li>
            </ol>
            {% endfor %}
        </div>

        <a class="to_form" href="{% url 'index' %}">Оставить заявку</a>

    </div>
</main>


{% include "app/footer.html" %}